project:
  type: manuscript

manuscript:
  notebooks:
    - notebook: code/03_explanal/3.1_descr_anal.qmd
  code-links: binder

execute: 
  freeze: auto

author:
  - name: Tristan Muno
    orcid: 0009-0002-3078-8436
    email: tristan.muno@uni-mannheim.de
    affiliations: 
      - name: University of Mannheim
        address: A 5, 6 – Raum A 351
        city: Mannheim
        state: BW
        postal-code: 68159
  - name: Thomas König
    orcid: 0000-0002-1797-6662
    email: koenig@uni-mannheim.de
    affiliations: 
      - name: University of Mannheim
        address: A 5, 6 – Raum A 353
        city: Mannheim
        state: BW
        postal-code: 68159 

bibliography: references.bib
biblio-style: apsr
link-citations: true
number-sections: true
date: last-modified
date-format: MMMM D, YYYY

format:
  html:
    citeproc: false
    filters:
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/citeproc.lua
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/wordcount.lua
    toc: true
  pdf:
    toc: false
    toc-depth: 3
    include-in-header:
      text: |
        \usepackage{setspace}
        \setlength{\parindent}{15pt}
        \usepackage[font=footnotesize]{caption}
    thanks: |
      Space for acknowledgements.
      Wordcount: {{< words-body >}}.
    papersize: a4
    fontsize: 12pt
    linestretch: 2
    geometry:
      - top = 2cm
      - bottom = 2cm
      - left = 2.5cm
      - right = 2.5cm
      - footskip = 20pt
  docx: default